CREATE DATABASE BD_RESTAURANTE;
USE BD_RESTAURANTE;
CREATE TABLE `categoria` (
  `ID_CATEGORIA` int unsigned NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA` varchar(50) NOT NULL,
  `DES_CATEGORIA` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `subcategoria` (
  `ID_SUBCAT` int unsigned NOT NULL AUTO_INCREMENT,
  `ID_CATEGORIA` int unsigned NOT NULL,
  `NOMBRE_SUBCAT` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_SUBCAT`,`ID_CATEGORIA`),
  KEY `FK_subcategoria` (`ID_CATEGORIA`),
  CONSTRAINT `FK_subcategoria` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `categoria` (`ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `producto` (
  `PRODUCTO_ID` int unsigned NOT NULL AUTO_INCREMENT,
  `PRODUCTO_NOMBRE` varchar(100) NOT NULL,
  `descripcion` varchar(500) NOT NULL,
  `PRECIO_UNITARIO` decimal(8,2) NOT NULL,
  `STOCK` int NOT NULL,
  `ID_CATEGORIA` int unsigned NOT NULL,
  `ID_SUBCAT` int unsigned NOT NULL,
  foto varchar(500) not null,
  `ESTADO` int NOT NULL,
  PRIMARY KEY (`PRODUCTO_ID`),
  KEY `FK_producto_cat` (`ID_CATEGORIA`),
  KEY `FK_producto_subcat` (`ID_SUBCAT`,`ID_CATEGORIA`),
  CONSTRAINT `FK_producto_cat` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `categoria` (`ID_CATEGORIA`),
  CONSTRAINT `FK_producto_subcat` FOREIGN KEY (`ID_SUBCAT`, `ID_CATEGORIA`) REFERENCES `subcategoria` (`ID_SUBCAT`, `ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*SCRIPB*/

select s.ID_SUBCAT,c.ID_CATEGORIA,s.NOMBRE_SUBCAT,c.NOMBRE_CATEGORIA from subcategoria s

INNER JOIN categoria c ON s.ID_CATEGORIA = c.ID_CATEGORIA order by c.NOMBRE_CATEGORIA asc;

select s.ID_SUBCAT,c.ID_CATEGORIA,s.NOMBRE_SUBCAT,c.NOMBRE_CATEGORIA from subcategoria s

INNER JOIN categoria c ON s.ID_CATEGORIA = c.ID_CATEGORIA where c.NOMBRE_CATEGORIA LIKE '%carne%' or c.NOMBRE_CATEGORIA LIKE '%lacteos%' 
order by c.NOMBRE_CATEGORIA asc;
